### PR TITLE
feat: whoami method is added to me client

### PR DESCRIPTION
**Pull request by itmsh**
whoami method is added to me client

## Description

new client added for me endpoint and the whoami method can be called directly on this client

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

If you're unsure about any of these, don't hesitate to ask. We're here to help!

### CODE REVIEW

**Review by vbarzana — APPROVED** [review]
Looks good to me, if you tested it! Go ahead and merge it

**Review by nicoorfi — APPROVED** [review]
Seems good :)

**Comment by vbarzana** [comment]
Sorry guys, this is too messy, the whole object oriented structure here is messed up, too many write/readClient and what not to me that doesn't sound understandable, too many objects. The me/whoami is just a custom call. Let's say we close this here and have a better clean class structure here, but definitely the whole thing of clients and entities is not correct IMHO.

**Comment by vbarzana** [comment]
As agreed with Masoud, we won't merge this, we will create a new PR

**Pull request closed without merging**
